source 'https://rubygems.org'

gem 'sinatra'
gem 'slim'
gem 'sqlite3'
gem 'rerun'
gem 'bcrypt'
gem 'byebug'
gem 'capybara'
gem 'rspec'
gem 'selenium-webdriver'
gem 'chromedriver-helper', '1.2.0'
gem 'sinatra-flash'
